# Generated by Django 2.1.8 on 2019-10-31 15:44

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Buyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('number', models.IntegerField()),
                ('production', models.DateTimeField()),
                ('safe_date', models.CharField(max_length=32)),
                ('picture', models.ImageField(default='shop/img/1,jpg', upload_to='shop/img')),
                ('description', ckeditor.fields.RichTextField()),
                ('statue', models.IntegerField()),
                ('goods_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.GoodsType')),
            ],
        ),
    ]
