# Generated by Django 2.1.8 on 2019-11-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(default='image/photo.jpeg', upload_to='image')),
            ],
        ),
    ]
